### ISSUE TITLE
User Role

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#1]
|FR1.  User Role|
|---|
|**Goal**: The app will allow users to sign up with a user profile.|
**Stakeholders:** Disabled Users|
| **Description:** When a user loads the website they will be given the option to login or sign up. Upon clicking sign up it will ask are they registering as a user or an owner. Users will be able to add a description of their disabilities and add a profile picture for their account.|
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 1 |

**Comment by KenGajefski** [comment]
Done, but in limited capacity. Profiles work, we just need to add a form on sign-up for tracking disabilities.
