### ISSUE TITLE
Owner Role

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#10]
|FR10. Owner Role |
|---|
|**Goal**: The Profile will have an option for business owners to add information about their establishment. 
**Stakeholders:** Business Owners|
| **Description:** Business Owners can sign up for a regular profile, and have the option to create a business owner role so that they can add accessibility information about their establishment, as well as upload pictures.|
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 2|

**Comment by ga9028** [comment]
Unfortunately, we were unable to add the owner role page.
