### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#13]
|FR13. Camera|
|---|
|**Goal**: The customers and critics will have the option to take pictures for comments and reviews.|
**Stakeholders:** All|
| **Description:** The app will have the ability to access your camera so that you may take a picture of establishments. Since the app is already connected to the camera, there will be no need to import the taken picture. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 3|

**Comment by ga9028** [comment]
Camera was no longer a feature we were trying to add to our project.
