### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#14]
|FR14.  Language|
|---|
|**Goal**: All users will be able to select from a few different languages to view the website in. |
**Stakeholders:** All|
| **Description:** We don’t want to exclude anybody from visiting our site due to a language barrier. Users will be able to go to a section in settings to select from a growing list of other languages to display the site in. As this is for disabled people, this might grow to include read out loud and text to speech functionality as well. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 3|

**Comment by ga9028** [comment]
Unfortunately, we were not able to achieve multiple language options
