### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#16]
|NFR1.  Performance|
|---|
|**Goal**: The website will need to process search calls and interaction within a reasonable time. |
**Stakeholders:** All|
| **Description:** The most likely scenario when a user is on the site is that they’ll be searching up a few places at a time. If these take more than a few seconds each to process from the user, the experience can be frustrating and cause them to not come back or quit using the site before they find what they were looking for initially. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 1|

**Comment by ga9028** [comment]
Congrats! We have maintained well performance throughout the project. The site doesn't crash when using and isn't laggy.
