### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#17]
|NFR2.  Usability|
|---|
|**Goal**: Our goal is to make our app usability as easy as possible.|
**Stakeholders:** All|
| **Description:** We want our website to have an easy learning curve when it comes to figuring out how to operate. We want the site to be able to take inputs in smoothly and interpret outputs so that people can understand the outcome.|
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 1|

**Comment by ga9028** [comment]
Congrats! We maintained usability throughout! The app has a very small learning curve and is overall easy to navigate.
