### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#18]
|NFR4.  Privacy|
|---|
|**Goal**: Sensitive user information will remain anonymous.|
**Stakeholders:** All|
| **Description:** When it comes to individual user names and information, the information will remain anonymous. Individual business owner names will also remain anonymous, but their business names will be visible. We want to make sure that sensitive information is protected, but integral information is visible - users should feel secure using the application and posting reviews that remain anonymous.|
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 1|

**Comment by ga9028** [comment]
We successfully achieved anonymous user information
