### ISSUE TITLE
Data Integrity

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#19]
|NFR5. Data Integrity|
|---|
|**Goal**: All the data entered will be assured to be accurate.|
**Stakeholders:** All|
| **Description:** Data entered users, business owners, and developers will be accurate and maintained.|
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 1|

**Comment by ga9028** [comment]
Congrats! We have maintained Data Integrity of users throughout the project process!
