### ISSUE TITLE
User Comments

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#2]
|FR2.  User Comments|
|---|
|**Goal**: The app will allow users to leave comments on location pages. |
**Stakeholders:** Disabled Users|
| **Description:** When a customer has been to a location and want to leave feedback on that location they will be allowed to go to the company page and write a review. Users and owners will be able to reply to each others comments.|
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 3 |

**Comment by ga9028** [comment]
Users can add comments for locations in the reviews tab
