### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#20]
|NFR3. Security|
|---|
|**Goal**:  Users personal data will be secure and inaccessible to other users.|
**Stakeholders:** All|
| **Description:** Users information will be kept secure through password use, authentication, and the use of SSL or TSL.|
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 1|

**Comment by ga9028** [comment]
Congrats! We completed this issue using hashing in our passwords!
