### ISSUE TITLE
User Ratings

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#3]
|FR3.  User Ratings|
|---|
|**Goal**: The user will be able to leave a quick rating on a 5 star scale for a location. |
**Stakeholders:** Disabled Users|
| **Description:** After a user has been to a location they can give a quick rating for the location if they don’t want to write out a review for it. Users will be able to give the location a rating on a 1-5 scale with 5 being the best and 1 being the worst.|
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 3 |

**Comment by ga9028** [comment]
Success! We were able to add the option to leave reviews on locations!
