### ISSUE TITLE
Filter by disability

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#5]
|FR5. Filter by disability|
|---|
|**Goal**: The system will allow the user to search for locations with accessibility features pertaining to a specific disability per location.|
**Stakeholders:** Disabled Users|
| **Description:** When a customer goes to the search bar, they will have an option to add filters. The filter by disability option will allow customers to add a disability that they need a business to have features for. Once they search with the filter, businesses that have accessibility features for that specific disability will be returned to the user in a list.|
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 2|

**Comment by ga9028** [comment]
We weren't able to add filters, but on the home page we have markers to show handicapped locations.
