### ISSUE TITLE
Filter by establishment type

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#6]
|FR6.  Filter by establishment type|
|---|
|**Goal**: The system will allow the user to search for specific accessibility features pertaining to a specific establishment type  in their area.|
**Stakeholders:** Disabled Users|
| **Description:** When a customer goes to the search bar, they will have an option to add filters. The filter by establishment option will allow customers to add an establishment type that they intend to visit and need accessibility features at. Once they search with the filter, the establishment types that have accessibility features in their local area will be returned to them in a list.|
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 2|

**Comment by ga9028** [comment]
We made it so you in the search bar you can search up establishment types and find different locations!
