### ISSUE TITLE
Favorite/Follow Location

### ISSUE THREAD

**Issue by laurel-walker** [WSU-4110/Able#9]
|FR9.  Favorite/Follow Location|
|---|
|**Goal**:   TThe system will allow users to mark locations which they particularly enjoyed as Favorited or Followed.|
**Stakeholders:** Disabled Users|
| **Description:** Customers will sometimes enjoy certain locations more than others. In order for the customer to not forget the location, they have the option to favorite/follow that place. For quicker access to your marked locations, they will have a special tab in the app.|
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/17/2019 | 
|  **Priority:** 3|

**Comment by ga9028** [comment]
Unfortunately, we were unable to include favorite locations.
